
export const portfolioItems: {
    id: string;
    title: string;
    category: string;
    type: 'webdev' | 'accounting' | 'ai';
    imageUrl: string;
    dataAiHint: string;
    description: string;
    longDescription: string;
    tags: string[];
    client: string;
    date: string;
    liveUrl: string;
    servicesProvided: string[];
    results: string;
    gallery: {
        src: string;
        alt: string;
        dataAiHint: string;
    }[];
}[] = [
  {
    id: 'tradyne-perfumes',
    title: 'Tradyne Perfumes',
    category: 'E-commerce · Luxury Fragrance',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxwZXJmdW1lc3xlbnwwfHx8fDE3NTQzNzkwNTR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'regal perfume bottle TRADYNE Royale deep purple sapphire blue glass gold accents embossed logo rich velvet royal fabric purple midnight blue background spotlight subtle sparkles classy royal powerful',
    description: 'A sophisticated e-store for Tradyne Perfumes, featuring seamless product browsing, a mobile-first design, and secure payments via Razorpay.',
    longDescription: 'Tradyne Perfumes required a high-end online presence to match their luxury products. We developed a custom, SEO-friendly e-commerce platform that is both visually elegant and highly functional. The site is fully mobile-responsive and incorporates Razorpay for secure and reliable payment processing, providing a seamless shopping experience for customers.',
    tags: ['E-commerce', 'Razorpay', 'Mobile Responsive', 'SEO'],
    client: 'Tradyne Trading',
    date: '2024-08-15',
    liveUrl: 'https://tradynetrading.com',
    servicesProvided: ['E-commerce Development', 'UI/UX Design', 'Razorpay Integration', 'Mobile Optimization', 'SEO Strategy'],
    results: 'Successfully launched a premium e-commerce store, enhancing brand image and enabling direct-to-consumer sales with a secure payment system.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1680984258298-8fc21dacce9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxwZXJmdW1lJTIwc3RvcmUlMjBob21lcGFnZXxlbnwwfHx8fDE3NTQzNzk5NTJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Tradyne Perfumes Homepage', dataAiHint: 'perfume store homepage' },
        { src: 'https://images.unsplash.com/photo-1563170352-ba54fb431add?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxmcmFncmFuY2UlMjBwcm9kdWN0fGVufDB8fHx8MTc1NDM3OTk1Mnww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Product Detail Page', dataAiHint: 'fragrance product' },
        { src: 'https://images.unsplash.com/photo-1726137570712-58609cab9eba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxwYXltZW50JTIwY2hlY2tvdXR8ZW58MHx8fHwxNzU0Mzc5OTUyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Secure Checkout with Razorpay', dataAiHint: 'payment checkout' },
    ]
  },
  {
    id: 'philotes-shoes',
    title: 'Philotes - The Shoe Brand',
    category: 'E-commerce · Footwear',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOXx8c2hvZXN8ZW58MHx8fHwxNzU0Mzc5MTEyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'stylish shoes pair',
    description: 'An online brand store for Philotes shoes, designed to showcase their unique footwear collection with a focus on user experience and mobile commerce.',
    longDescription: 'Philotes, a modern shoe brand, needed a digital storefront to capture their brand essence. We created a visually engaging e-store that highlights their product collection through high-quality imagery and intuitive navigation. The platform is optimized for mobile shopping and designed to be SEO-friendly to attract a wider audience.',
    tags: ['E-commerce', 'Brand Store', 'Footwear', 'SEO'],
    client: 'Philotes Multitrading',
    date: '2024-07-20',
    liveUrl: 'https://philotesmultitrading.com',
    servicesProvided: ['E-commerce Platform', 'Brand Website Design', 'Product Showcase', 'Mobile Commerce', 'SEO'],
    results: 'Established a strong online presence for the Philotes brand, resulting in increased brand awareness and online sales.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1618677831741-6260a73ff4f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxzaG9lJTIwY29sbGVjdGlvbnxlbnwwfHx8fDE3NTQzODAxNzd8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Philotes Shoe Collection', dataAiHint: 'shoe collection' },
        { src: 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxzaW5nbGUlMjBzaG9lfGVufDB8fHx8MTc1NDM4MDE3N3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Shoe Product Page', dataAiHint: 'single shoe' },
        { src: 'https://images.unsplash.com/photo-1586880244543-0528a802be97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxtb2JpbGUlMjBzaG9wcGluZ3xlbnwwfHx8fDE3NTQzODAxNzd8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Mobile Shopping Experience', dataAiHint: 'mobile shopping' },
    ]
  },
  {
    id: 'divyasangrah-spiritual-marketplace',
    title: 'DivyaSangrah Spiritual Marketplace',
    category: 'E‑commerce · Spiritual Services',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1639575668826-d6378418b110?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxwYW5kaXR8ZW58MHx8fHwxNzUwNDExMTIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'spiritual storefront',
    description: 'An all-in-one online store offering puja items, astrology consultations, and religious service bookings. Crafted for spiritual ambience and performance.',
    longDescription: 'An all-in-one online store offering puja items, astrology consultations, and religious service bookings. Crafted for spiritual ambience and performance, this platform utilizes WordPress for e-commerce with a custom booking system for services, providing a seamless user experience for spiritual seekers.',
    tags: ['WordPress', 'Religious E-commerce', 'Booking System', 'Astrology', 'Puja Items'],
    client: 'DivyaSangrah',
    date: '2024-01-15',
    liveUrl: 'https://divyasangrah.com',
    servicesProvided: ['WordPress Development', 'E-commerce Strategy', 'Booking System Integration', 'UI/UX Design', 'Payment Gateway Setup'],
    results: 'Successfully launched a comprehensive spiritual marketplace, leading to increased service bookings and product sales. Enhanced user engagement through intuitive design.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1565474087406-2d7e5b99b350?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxzdG9yZWZyb250JTIwaG9tZXxlbnwwfHx8fDE3NTQzODA1NjF8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Marketplace Homepage', dataAiHint: 'storefront home' },
        { src: 'https://images.unsplash.com/photo-1626207887298-da2fc1f50e82?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxzZXJ2aWNlJTIwYm9va2luZ3xlbnwwfHx8fDE3NTQzODA1NjF8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Astrology Consultation Booking', dataAiHint: 'service booking' },
        { src: 'https://images.unsplash.com/photo-1727963179460-5d1c8f5f96c8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxwdWphJTIwaXRlbXN8ZW58MHx8fHwxNzU0MzgwNTYxfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Puja Items Store', dataAiHint: 'puja items' },
    ]
  },
  {
    id: 'itverbs-technology-solutions',
    title: 'ITVerbs Technology Solutions',
    category: 'Corporate IT Solutions',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1556740714-a8395b3bf30f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MXwxfHNlYXJjaHw4fHxpdCUyMHRlY2glMjB8ZW58MHx8fHwxNzUwNDExMTg1fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'corporate it',
    description: 'Corporate portal for AI solutions, cloud services, and development projects. Includes career hub, portfolio sections, and contact workflows.',
    longDescription: 'A comprehensive corporate portal for ITVerbs, showcasing their expertise in AI, cloud services, and custom development. The platform features a dynamic career hub, detailed portfolio sections, and streamlined contact workflows to facilitate client engagement and talent acquisition.',
    tags: ['IT Website', 'AI Services', 'Tech Branding', 'Cloud Solutions', 'Career Portal'],
    client: 'ITVerbs Technology Solutions',
    date: '2024-02-01',
    liveUrl: 'https://www.itverbstechnologysolutions.com',
    servicesProvided: ['Corporate Website Design', 'AI Solutions Showcase', 'Cloud Services Info', 'Portfolio Development', 'Contact Integration'],
    results: 'Enhanced online presence and lead generation for IT services. Streamlined recruitment process through the integrated career hub.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1588610991095-734b1574b960?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxhdXRvbWF0aW9uJTIwcnVsZXN8ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'AI Solutions Page', dataAiHint: 'automation rules' },
        { src: 'https://images.unsplash.com/photo-1580484026799-aa3e7a76b3fc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjYXJlZXIlMjBwb3J0YWx8ZW58MHx8fHwxNzU0MzgxMjIwfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Career Hub Interface', dataAiHint: 'career portal' },
        { src: 'https://images.unsplash.com/photo-1727285100419-348edd55d403?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8Y2xpZW50JTIwd29ya3xlbnwwfHx8fDE3NTQzODEyMjF8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Client Portfolio Display', dataAiHint: 'client work' },
    ]
  },
  {
    id: 'buztrix-traveltech',
    title: 'BuzTrix TravelTech India Pvt. Ltd.',
    category: 'Travel SaaS Platform',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1726197799856-cdff7a9037b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxNXx8dHJhdmVsJTIwYW5kJTIwdG91cnxlbnwwfHx8fDE3NTA0MTEyNTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'travel saas',
    description: 'Developed for B2B travel operations. Offers hotel & flight APIs, lead tracking dashboards, and bulk booking systems.',
    longDescription: 'A robust B2B SaaS platform tailored for the travel industry. BuzTrix TravelTech features seamless integration with hotel and flight APIs, a comprehensive lead tracking dashboard, and efficient bulk booking systems, empowering travel agencies to optimize their operations.',
    tags: ['API Integration', 'Travel CRM', 'Booking Portal', 'SaaS Development', 'B2B Platform'],
    client: 'BuzTrix TravelTech India Pvt. Ltd.',
    date: '2023-12-10',
    liveUrl: 'http://buztrixtraveltechindiapvtltd.com',
    servicesProvided: ['SaaS App Development', 'Third-party API Integration', 'CRM Dashboard Design', 'Bulk Booking System', 'User Role Management'],
    results: 'Streamlined B2B travel operations for numerous clients, improving booking efficiency and lead management.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1627921842419-15e475c4d2e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxzYWFzJTIwZGFzaGJvYXJkfGVufDB8fHx8MTc1NDM4Njg5MHww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Travel API Dashboard', dataAiHint: 'saas dashboard' },
        { src: 'https://images.unsplash.com/photo-1721855806374-4285051c3b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxsZWFkJTIwdHJhY2tpbmd8ZW58MHx8fHwxNzU0Mzg2ODkxfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Lead Tracking System', dataAiHint: 'lead tracking' },
        { src: 'https://images.unsplash.com/photo-1707301452478-ad6df0ab40f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxiMmIlMjBwb3J0YWx8ZW58MHx8fHwxNzU0Mzg2ODkwfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Bulk Booking Interface', dataAiHint: 'b2b portal' },
    ]
  },
  {
    id: 'brista-travels',
    title: 'Brista Travels Pvt. Ltd.',
    category: 'Travel & Tours Website',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1500835556837-99ac94a94552?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHx0cmF2ZWx8ZW58MHx8fHwxNzUwNDExMzM5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'travel booking',
    description: 'Travel booking site highlighting packages, destination guides, and lead forms with WhatsApp integration.',
    longDescription: 'Brista Travels\' website is designed to attract and convert travelers with stunning destination showcases, detailed package information, and easy-to-use lead generation forms integrated with WhatsApp for quick communication.',
    tags: ['UX Design', 'Lead Funnels', 'Destination Portfolio', 'Travel Website', 'WhatsApp Integration'],
    client: 'Brista Travels Pvt. Ltd.',
    date: '2023-11-05',
    liveUrl: 'http://bristatravelspvtltd.com',
    servicesProvided: ['Travel Website Design', 'UX/UI for Tourism', 'Lead Generation Forms', 'WhatsApp Integration', 'CMS'],
    results: 'Increased lead generation by 30% through optimized user funnels and direct WhatsApp engagement.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1561538165-411322e90881?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8dG91ciUyMHBhY2thZ2VzfGVufDB8fHx8MTc1NDM4OTExM3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Travel Package Display', dataAiHint: 'tour packages' },
        { src: 'https://images.unsplash.com/photo-1526904701202-d6ccd5c4b9ac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxkZXN0aW5hdGlvbiUyMGluZm98ZW58MHx8fHwxNzU0Mzg5MTEzfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Destination Guide Page', dataAiHint: 'destination info' },
        { src: 'https://images.unsplash.com/photo-1578016981482-d4dd3db297b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxib29raW5nJTIwZm9ybXxlbnwwfHx8fDE3NTQzODkxMTJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Lead Form with WhatsApp', dataAiHint: 'booking form' },
    ]
  },
  {
    id: 'taskslate-productivity-tool',
    title: 'TaskSlate Productivity Tool',
    category: 'Productivity SaaS',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx0ZWNofGVufDB8fHx8MTc1MDQwNTQyNnww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'productivity app',
    description: 'Multi-user task manager with role permissions, calendar views, and file sharing. Built for freelancers and small businesses.',
    longDescription: 'TaskSlate is a web-based productivity SaaS application designed for freelancers and small teams. It features robust multi-user task management, role-based permissions, intuitive calendar views, and secure file sharing capabilities to enhance workflow efficiency.',
    tags: ['Web App', 'Workflow SaaS', 'Productivity Tools', 'Task Management', 'Collaboration'],
    client: 'TaskSlate Inc.',
    date: '2023-10-20',
    liveUrl: 'https://taskslate.in',
    servicesProvided: ['SaaS App Development', 'User Authentication', 'Calendar Integration', 'File Management', 'Real-time Collaboration'],
    results: 'Empowered small businesses and freelancers with an effective tool for task management and team collaboration.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1683199320521-38e3370de70d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxwcm9qZWN0JTIwdGFza3N8ZW58MHx8fHwxNzU0MzkwMzc1fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Task Management Dashboard', dataAiHint: 'project tasks' },
        { src: 'https://images.unsplash.com/photo-1676276376052-dc9c9c0b6917?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHx0ZWFtJTIwY2FsZW5kYXJ8ZW58MHx8fHwxNzU0MzkwMzc1fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Calendar View', dataAiHint: 'team calendar' },
        { src: 'https://images.unsplash.com/photo-1528157377481-b010149f0e4c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxkb2N1bWVudCUyMGNsb3VkfGVufDB8fHx8MTc1NDM5MDM3NXww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'File Sharing Interface', dataAiHint: 'document cloud' },
    ]
  },
  {
    id: 'parivartan-by-divyasangrah',
    title: 'Parivartan by DivyaSangrah',
    category: 'E-commerce · Apparel Store',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1555529771-835f59fc5efe?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxhcHBhcmVsfGVufDB8fHx8fDE3NTUwNDExgzOHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'apparel store',
    description: 'An online apparel store by DivyaSangrah, offering a unique collection of clothing and accessories. Designed for a seamless shopping experience.',
    longDescription: "Parivartan by DivyaSangrah is an e-commerce platform dedicated to apparel, offering a unique collection of clothing and accessories. The store is designed to provide a seamless and enjoyable online shopping experience, showcasing fashion items with style and elegance.",
    tags: ['E-commerce', 'Apparel', 'Fashion', 'Online Shopping', 'Clothing Store'],
    client: 'DivyaSangrah',
    date: '2023-09-15',
    liveUrl: 'https://parivartan.divyasangrah.com',
    servicesProvided: ['E-commerce Platform Development', 'Online Store Design', 'Product Catalog Management', 'Payment Gateway Integration', 'Fashion E-commerce'],
    results: "Successfully launched a stylish online apparel store, attracting fashion-conscious customers and increasing online sales.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1542295669-1273616f7fd6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxjbG90aGluZyUyMGNvbGxlY3Rpb258ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Apparel Collection Showcase', dataAiHint: 'clothing collection' },
        { src: 'https://images.unsplash.com/photo-1581044777550-4cfa6ce998c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwcHJvZHVjdHxlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Product Detail Page', dataAiHint: 'fashion product' },
        { src: 'https://images.unsplash.com/photo-1583255113824-d258a47480a4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxlY29tbWVyY2UlMjBjaGVja291dHxlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Online Store Checkout', dataAiHint: 'ecommerce checkout' },
    ]
  },
  {
    id: 'anandam-wellness-hub', 
    title: 'Anandam by DivyaSangrah',
    category: 'Food & Restaurant · Online Ordering',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw1fHxpbmRpYW4lMjBmb29kfGVufDB8fHx8fDE3NTUwNDEyNDgzfDA&ixlib=rb-4.1.0&q=80&w=1080', 
    dataAiHint: 'food restaurant', 
    description: 'Online store for delicious meals and restaurant services. Features menu display, online ordering, and table reservations.', 
    longDescription: 'Anandam by DivyaSangrah offers a delightful online experience for food lovers. Browse our extensive menu, place orders for delivery or pickup, and even book a table. The platform is designed for ease of use, showcasing delicious food photography and providing a seamless ordering process.', 
    tags: ['Online Ordering', 'Restaurant Website', 'Food Delivery', 'Menu Management'], 
    client: 'DivyaSangrah', 
    date: '2023-08-01', 
    liveUrl: 'https://anandam.divyasangrah.com', 
    servicesProvided: ['Online Ordering System', 'Menu Management Integration', 'Restaurant Website Design', 'Payment Gateway Setup', 'Table Reservation Feature'], 
    results: 'Successfully launched an intuitive online food ordering platform, increasing takeaway orders and streamlining the reservation process. Positive customer feedback on ease of use and menu presentation.', 
    gallery: [ 
        { src: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxmb29kJTIwbWVudXxlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Restaurant Menu Page', dataAiHint: 'food menu' },
        { src: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxvcmRlciUyMGZvb2R8ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Online Ordering System', dataAiHint: 'order food' },
        { src: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxyZXN0YXVyYW50JTIwYm9va2luZ3xlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Table Reservation Interface', dataAiHint: 'restaurant booking' },
    ]
  },
  {
    id: 'divinepartners-consulting',
    title: 'DivinePartners Consulting',
    category: 'Corporate · Consulting',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjb25zdWx0YW5jeXxlbnwwfHx8fDE3NTA0MTI2NTZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'consulting website',
    description: 'Clean and professional consultancy website. Features services, dynamic forms, and CRM integrations.',
    longDescription: 'DivinePartners Consulting required a polished and professional online presence. We delivered a clean website that clearly outlines their services, incorporates dynamic lead capture forms, and integrates seamlessly with their CRM for efficient client management.',
    tags: ['Corporate Design', 'Forms', 'Client Management', 'Consulting Website', 'CRM Integration'],
    client: 'DivinePartners Consulting',
    date: '2023-07-10',
    liveUrl: 'https://divinepartners.com',
    servicesProvided: ['Professional Web Design', 'Dynamic Form Creation', 'CRM Integration', 'Service Page Layouts', 'Mobile Responsive Dev'],
    results: 'Improved professional image and streamlined lead management process, resulting in better client acquisition.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxjb25zdWx0aW5nJTIwc2VydmljZXN8ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Consulting Services Page', dataAiHint: 'consulting services' },
        { src: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxpbnF1aXJ5JTIwZm9ybXxlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Dynamic Contact Form', dataAiHint: 'inquiry form' },
        { src: 'https://images.unsplash.com/photo-1616401784845-180844d1baed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjcm0lMjBmbG93fGVufDB8fHx8MTc1NDQ3Mjc4Mnww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'CRM Integration Diagram', dataAiHint: 'crm flow' },
    ]
  },
  {
    id: 'venkwara-infotech',
    title: 'Venkwara Infotech Pvt. Ltd.',
    category: 'IT & Web Services',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxhY2NvdW50YW5jeXxlbnwwfHx8fDE3NTA0MTM1Njh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'it services website',
    description: 'Technology-focused site showcasing development and infrastructure projects. Includes client portfolios and contact automation.',
    longDescription: 'Venkwara Infotech\'s website serves as a showcase for their extensive development and IT infrastructure projects. The site features detailed client portfolios and automated contact systems to effectively demonstrate their capabilities and engage potential clients.',
    tags: ['Enterprise Web', 'Tech Branding', 'DevOps', 'IT Solutions', 'Client Portfolio'],
    client: 'Venkwara Infotech Pvt. Ltd.',
    date: '2023-06-05',
    liveUrl: 'https://venkwarainfotechpvtltd.com',
    servicesProvided: ['Tech Website Development', 'Client Portfolio Design', 'Contact Automation', 'DevOps Solutions', 'Infrastructure Projects'],
    results: 'Successfully showcased complex IT projects, enhancing credibility and attracting enterprise-level clients.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxkZXYlMjBwcm9qZWN0c3xlbnwwfHx8fDE3NTQ0NzI3ODN8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Development Projects Showcase', dataAiHint: 'dev projects' },
        { src: 'https://images.unsplash.com/photo-1573495782789-70762a1b5c8a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjbG91ZCUyMGluZnJhfGVufDB8fHx8MTc1NDQ3Mjc4M3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Infrastructure Solutions', dataAiHint: 'cloud infra' },
        { src: 'https://images.unsplash.com/photo-1611926653458-092a4234cfb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhdXRvbWF0aW9uJTIwcnVsZXMlMjBzZXR1cHxlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Automated Contact System', dataAiHint: 'automation rules' },
    ]
  },
  {
    id: 'talentgrowth-id',
    title: 'TalentGrowth ID',
    category: 'Career & HR Tech',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1675654567523-b19d60eb4d3d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0YWxlbnQlMjBncm93dGglMjBpdHxlbnwwfHx8fDE3NTA0MzM5NDl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'career platform',
    description: 'Indonesia-based talent development platform. Personalized job matching, growth tracking, and candidate profiling system.',
    longDescription: 'TalentGrowth ID is an innovative Indonesian platform for talent development. It offers personalized job matching, career growth tracking, and detailed candidate profiling systems to connect job seekers with opportunities and help companies find the right talent.',
    tags: ['EdTech', 'Career Platform', 'Job Board', 'HR Technology', 'Talent Matching'],
    client: 'TalentGrowth Indonesia',
    date: '2024-03-01',
    liveUrl: 'https://www.talentgrowth.id/',
    servicesProvided: ['Platform Development', 'Matching Algorithm', 'Growth Tracking', 'Candidate Profiling', 'Job Board'],
    results: 'Launched a unique talent development platform in the Indonesian market, connecting skilled individuals with employers.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1556740758-90de374c12ad?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxncm93dGglMjBkYXNoYm9hcmR8ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Job Matching Interface', dataAiHint: 'growth dashboard' },
        { src: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjYW5kaWRhdGUlMjBwcm9maWxlfGVufDB8fHx8MTc1NDQ3Mjc4Mnww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Candidate Profile', dataAiHint: 'candidate profile' },
        { src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxncm93dGglMjBkYXNoYm9hcmR8ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Growth Tracking Dashboard', dataAiHint: 'growth dashboard' },
    ]
  },
  {
    id: 'nirogitanman-healthcare',
    title: 'Nirogitanman Healthcare',
    category: 'Health Portal · Ayurvedic Wellness',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxoZWFsdGglMjB8ZW58MHx8fHwxNzUwNDM0MjcwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'ayurvedic healthcare',
    description: 'Online consultation portal with Ayurveda-based health products and doctor booking. Simple UI and multilingual support.',
    longDescription: 'Nirogitanman Healthcare provides an accessible online portal for Ayurvedic wellness. It features online doctor consultations, a marketplace for Ayurveda-based products, and an easy-to-use booking system, all with a simple UI and multilingual support for broader reach.',
    tags: ['Healthcare UX', 'Booking Integration', 'Ayurvedic E‑commerce', 'Telemedicine', 'Multilingual Website'],
    client: 'Nirogitanman Healthcare',
    date: '2024-04-10',
    liveUrl: 'https://nirogitanman.com/',
    servicesProvided: ['Healthcare Portal Dev', 'Doctor Booking System', 'Ayurvedic E-commerce', 'Multilingual Support', 'UI/UX Design'],
    results: 'Successfully launched an online Ayurvedic consultation and product platform, making traditional healthcare more accessible.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxvbmxpbmUlMjBjb25zdWx0YXRpb258ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Doctor Consultation Booking', dataAiHint: 'online consultation' },
        { src: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHwheXVydmVkYSUyMHByb2R1Y3RzfGVufDB8fHx8MTc1NDQ3Mjc4Mnww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Ayurvedic Product Store', dataAiHint: 'ayurveda products' },
        { src: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxtdWx0aWxpbmd1YWwlMjB1aXxlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Multilingual Interface', dataAiHint: 'multilingual ui' },
    ]
  },
  {
    id: 'indialends',
    title: 'IndiaLends',
    category: 'Fintech · Loan Marketplace',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1430276084627-789fe55a6da0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxMRU5EU3xlbnwwfHx8fDE3NTQzOTI1NjB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'fintech loan',
    description: 'Smart credit platform offering personal loans, credit cards, and financial education. Built with API-backed services and real-time checks.',
    longDescription: 'IndiaLends is a leading fintech platform in India, offering a smart credit marketplace for personal loans, credit cards, and financial literacy resources. The platform is built with robust API-backed services and real-time credit checking capabilities to provide users with quick and reliable financial solutions.',
    tags: ['Fintech UX', 'API', 'Loan Application', 'Credit Marketplace', 'Financial Education'],
    client: 'IndiaLends',
    date: '2024-05-20',
    liveUrl: 'https://www.indialends.com/',
    servicesProvided: ['Fintech Platform Dev', 'Financial API Integration', 'Loan Workflow Design', 'Credit Marketplace', 'Secure Data Handling'],
    results: 'Contributed to a high-traffic fintech platform, enhancing its loan and credit card application processes.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1639755491373-0490b42907e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxvYW4lMjBmb3JtfGVufDB8fHx8MTc1NDQ3Mjc4M3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Loan Application Form', dataAiHint: 'loan form' },
        { src: 'https://images.unsplash.com/photo-1556740738-b6a63e2775d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjYXJkJTIwY29tcGFyaXNvbnxlbnwwfHx8fDE3NTQ0NzI3ODN8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Credit Card Comparison', dataAiHint: 'card comparison' },
        { src: 'https://images.unsplash.com/photo-1620712943543-95fc636a843a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxpbmFuY2UlMjBlZHVjYXRpb258ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Financial Education Section', dataAiHint: 'finance education' },
    ]
  },
  {
    id: 'aadideva-venture',
    title: 'AadiDeva Venture',
    category: 'Travel & Adventure · Tour Booking',
    type: 'webdev',
    imageUrl: 'https://images.unsplash.com/photo-1540359319315-f69be3a17e9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxyZWFsZXN0YXRlfGVufDB8fHx8MTc1NDM5MzU1NHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'adventure booking',
    description: 'An adventure tourism platform offering curated trekking, cultural trips, and personalized travel experiences across India. Built to inspire explorers and manage bookings with ease.',
    longDescription: 'AadiDeva Venture is an online platform dedicated to adventure tourism in India. It offers a curated selection of trekking expeditions, cultural tours, and personalized travel itineraries, designed to inspire exploration and simplify the booking process for adventurers.',
    tags: ['Adventure Travel', 'Tour Portal', 'Booking Integration', 'Travel Experiences', 'Indian Tourism'],
    client: 'AadiDeva Venture',
    date: '2023-08-25',
    liveUrl: '#', 
    servicesProvided: ['Adventure Tourism Platform', 'Tour Curation', 'Online Booking System', 'Itinerary Builder', 'Travel CMS'],
    results: 'Launched an engaging platform for adventure travel, attracting explorers and streamlining tour bookings.',
    gallery: [
        { src: 'https://images.unsplash.com/photo-1551632811-561732d1e306?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0cmVra2luZyUyMHRvdXJ8ZW58MHx8fHwxNzU0NDcyNzgyfDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Trekking Package Showcase', dataAiHint: 'trekking tour' },
        { src: 'https://images.unsplash.com/photo-1534469534237-4a7d6d36e2f8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjdWx0dXJlJTIwdHJpcHxlbnwwfHx8fDE3NTQ0NzI3ODJ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Cultural Trip Booking', dataAiHint: 'culture trip' },
        { src: 'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0cmF2ZWwlMjBwbGFubmVyfGVufDB8fHx8MTc1NDQ3Mjc4Mnww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Personalized Travel Planner', dataAiHint: 'travel planner' },
    ]
  },
  {
    id: 'multi-currency-invoice-generation',
    title: 'Multi-Currency Invoice Generation',
    category: 'Financial Tools · International Invoicing',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1579500669315-99e9cdd932f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOHx8bXVsdGklMjBjdXJyZW5jeXxlbnwwfHx8fDE3NTQ0NzMyOTJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'invoice currency',
    description: 'Create invoices in USD, EUR, GBP, AED, and more with auto currency conversion and dual-currency display.',
    longDescription: 'Efficiently generate invoices in multiple currencies like USD, EUR, GBP, AED, etc. Features automatic currency conversion using real-time exchange rates and options for dual-currency display (e.g., INR + Foreign Currency) to cater to international clients.',
    tags: ["Invoicing", "Multi-Currency", "Forex", "Billing"],
    client: 'Global Businesses',
    date: '2024-06-01',
    liveUrl: '#',
    servicesProvided: ["Multi-Currency Invoicing", "Real-time Exchange Rates", "Dual-Currency Display", "International Billing Solutions"],
    results: "Streamlined international invoicing processes, improving clarity and payment efficiency for businesses with global clientele.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1643465494208-1f37e4544a95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjdXJyZW5jeSUyMHNldHRpbmdzfGVufDB8fHx8MTc1NDQ3Mjc4M3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Currency Settings Interface', dataAiHint: 'currency settings' },
        { src: 'https://images.unsplash.com/photo-1542844274-1b79529d3a09?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxpbnZvaWNlJTIwcHJldmlld3xlbnwwfHx8fDE3NTQ0NzI3ODN8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Sample Multi-Currency Invoice', dataAiHint: 'invoice preview' },
        { src: 'https://images.unsplash.com/photo-1559526324-c1f275fbfa32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxlc2NoYW5nZS1yYXRlc3xlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Exchange Rate Integration Display', dataAiHint: 'exchange rates' },
    ]
  },
  {
    id: 'international-tax-compliance',
    title: 'International Tax Compliance Solution',
    category: 'Taxation · Global Trade',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-1696413565d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0YXglMjBjb21wbGlhbmNlfGVufDB8fHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'tax compliance',
    description: 'Navigate GST with Export Invoice Format, LUT assistance, and country-specific tax breakdowns for seamless global trade.',
    longDescription: 'Ensures international tax compliance with features like GST-compliant Export Invoice Format, assistance with Letter of Undertaking (LUT), and detailed country-specific tax breakdowns (VAT, GST, etc.) for businesses involved in global trade.',
    tags: ["Taxation", "GST", "Export", "LUT", "VAT"],
    client: 'Exporters & Importers',
    date: '2024-06-05',
    liveUrl: '#',
    servicesProvided: ["Export Tax Compliance", "GST Export Invoicing", "LUT Assistance", "International VAT/GST Handling"],
    results: "Simplified tax compliance for international transactions, reducing errors and ensuring adherence to global tax regulations.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0YXglMjBmb3JtfGVufDB8fHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Tax Compliance Dashboard', dataAiHint: 'tax form' },
        { src: 'https://images.unsplash.com/photo-1605799902640-19d2d8293998?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxlc3BvcnQlMjBkb2N1bWVudHxlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Export Document Sample', dataAiHint: 'export document' },
        { src: 'https://images.unsplash.com/photo-1599891041539-71d533503f77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhc3NldCUyMG1hbmFnZW1lbnR8ZW58MHx8fHwxNzU0NDczODA2fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Compliance Checklist Feature', dataAiHint: 'asset management' },
    ]
  },
  {
    id: 'professional-invoice-customization',
    title: 'Professional Invoice Customization',
    category: 'Branding · Billing Solutions',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1583521214693-7de59641264a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxpbnZvaWNlJTIwZGVzaWdufGVufDB8fHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'invoice design',
    description: 'Offer branded invoice templates, multi-language options, and direct PDF download/email delivery to clients for a professional touch.',
    longDescription: 'Enhance your brand\'s professionalism with customizable invoice templates. Supports multi-language options for invoices, and allows for easy PDF download and direct email delivery to clients.',
    tags: ["Invoice Design", "Branding", "Multi-language", "PDF Invoices"],
    client: 'Service Businesses',
    date: '2024-06-10',
    liveUrl: '#',
    servicesProvided: ["Custom Invoice Templates", "Branded Invoicing", "Multi-Language Support", "PDF Generation & Delivery"],
    results: "Improved brand perception and client communication through professional and customizable invoicing.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1586953208448-315013527112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHx0ZW1wbGF0ZSUyMGVkaXRvcnxlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Invoice Template Editor', dataAiHint: 'template editor' },
        { src: 'https://images.unsplash.com/photo-1600880292210-859b923841e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjYXJkcyUyMGJyYW5kZWR8ZW58MHx8fHwxNzU0NDczODA2fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Branded Invoice Example', dataAiHint: 'cards branded' },
        { src: 'https://images.unsplash.com/photo-1628155930542-e4f1a1835616?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxsYW5ndWFnZSUyMG9wdGlvbnN8ZW58MHx8fHwxNzU0NDczODA2fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Multi-Language Invoice Options', dataAiHint: 'language options' },
    ]
  },
  {
    id: 'payment-integration-international',
    title: 'International Payment Gateway Integration',
    category: 'Fintech · Global Payments',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxwYXltZW50fGVufDB8fHx8MTc1NDQ3MjU4OHww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'payment gateway',
    description: 'Integrate payment gateways like PayPal, Stripe, Wise, Razorpay International, with payment reminders and a secure tracking dashboard.',
    longDescription: 'Facilitate seamless international payments by integrating popular gateways such as PayPal, Stripe, Wise, and Razorpay International. Includes features like payment due reminders, follow-ups, and a secure payment tracking dashboard.',
    tags: ["Payment Gateway", "PayPal", "Stripe", "International Payments"],
    client: 'Online Sellers & Freelancers',
    date: '2024-06-15',
    liveUrl: '#',
    servicesProvided: ["Payment Gateway Integration", "International Payment Processing", "Automated Reminders", "Payment Tracking"],
    results: "Increased international sales and faster payment collection by offering diverse and secure payment options.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1616401784845-180844d1baed?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxnYXRld2F5JTIwbG9nb3N8ZW58MHx8fHwxNzU0NDczODA2fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Payment Gateway Selection', dataAiHint: 'gateway logos' },
        { src: 'https://images.unsplash.com/photo-1604145610813-a402319d6537?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwYXltZW50JTIwZm9ybXxlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Secure Payment Form', dataAiHint: 'payment form' },
        { src: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwYXltZW50JTIwdHJhY2tpbmclMjBkYXNoYm9hcmR8ZW58MHx8fHwxNzU0NDczODA2fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Payment Tracking Dashboard', dataAiHint: 'tracking dashboard' },
    ]
  },
  {
    id: 'invoice-automation-scheduling',
    title: 'Invoice Automation & Scheduling System',
    category: 'Automation · Billing Efficiency',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxhdXRvbWF0aW9ufGVufDB8fHx8MTc1NDQ3MTkwMXww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'invoice automation',
    description: 'Automate monthly/recurring invoices, schedule dispatch via Email or WhatsApp, and send auto payment confirmations.',
    longDescription: 'Streamline your billing process with invoice automation. Auto-generate monthly or recurring invoices, schedule their dispatch through Email or WhatsApp, and send automatic payment confirmation messages to clients.',
    tags: ["Automation", "Recurring Billing", "Scheduled Invoices", "WhatsApp Billing"],
    client: 'Subscription Businesses',
    date: '2024-06-20',
    liveUrl: '#',
    servicesProvided: ["Recurring Invoice Automation", "Scheduled Dispatch (Email/WhatsApp)", "Automated Payment Confirmations", "Billing Workflow Optimization"],
    results: "Reduced manual effort and improved cash flow through efficient invoice automation and scheduling.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1678107373363-2287913ab9a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxpbnZvaWNlJTIwc2NoZWR1bGluZyUyMGludGVyZmFjZXxlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Invoice Scheduling Interface', dataAiHint: 'scheduling interface' },
        { src: 'https://images.unsplash.com/photo-1611926653458-092a4234cfb2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxhdXRvbWF0aW9uJTIwcnVsZXMlMjBzZXR1cHxlbnwwfHx8fDE3NTQ0NzM4MDZ8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Automation Rules Setup', dataAiHint: 'automation rules' },
        { src: 'https://images.unsplash.com/photo-1586953208448-315013527112?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxub3RpZmljYXRpb24lMjBzZXR0aW5ncyUyMHBhbmVsfGVufDB8fHx8MTc1NDQ3MzgwNnww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Notification Settings Panel', dataAiHint: 'notification settings' },
    ]
  },
  {
    id: 'record-keeping-reporting-suite',
    title: 'Advanced Record Keeping & Reporting Suite',
    category: 'Accounting · Financial Reporting',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1693045181224-9fc2f954f054?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxpbnZvaWNlfGVufDB8fHx8MTc1NDQ3MTUxN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'financial reports',
    description: 'Export/import invoice records, generate monthly/quarterly billing summaries, and integrate with Zoho, QuickBooks, Tally.',
    longDescription: 'Maintain accurate financial records with features to export/import invoice data. Generate monthly/quarterly billing summary reports and integrate seamlessly with popular accounting tools like Zoho, QuickBooks, and Tally.',
    tags: ["Accounting", "Reporting", "Zoho", "QuickBooks", "Tally"],
    client: 'Small & Medium Enterprises',
    date: '2024-06-25',
    liveUrl: '#',
    servicesProvided: ["Invoice Data Management", "Billing Summary Reports", "Accounting Software Integration", "Financial Record Keeping"],
    results: "Enhanced financial visibility and simplified accounting processes through robust record keeping and reporting.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1642070442304-453510c4109b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxyZXBvcnQlMjBkYXNoYm9hcmR8ZW58MHx8fHwxNzU0NDczODA3fDA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Financial Report Dashboard', dataAiHint: 'report dashboard' },
        { src: 'https://images.unsplash.com/photo-1633409361618-6874e053a47b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxkYXRhJTIwZXhwb3J0fGVufDB8fHx8MTc1NDQ3MzgwN3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Data Export Options', dataAiHint: 'data export' },
        { src: 'https://images.unsplash.com/photo-1651044458421-7c9e1b5a4a55?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxpbnRlZ3JhdGlvbiUyMGxvZ29zfGVufDB8fHx8MTc1NDQ3MzgwN3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Accounting Tool Integration Logos', dataAiHint: 'integration logos' },
    ]
  },
  {
    id: 'import-export-documentation-support',
    title: 'Import/Export Documentation Support',
    category: 'Global Trade · Logistics',
    type: 'accounting',
    imageUrl: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHx0cmFkZXxlbnwwfHx8fDE3NTQ0NjY5Mjh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    dataAiHint: 'export documents',
    description: 'Support for commercial invoice preparation, packing lists, shipping bills, and client KYC/agreement documentation tracking.',
    longDescription: 'Comprehensive support for import/export documentation, including commercial invoice preparation, packing lists, shipping bills, and tracking of client KYC and agreement documentation to ensure smooth international trade operations.',
    tags: ["Export Documentation", "Import Documentation", "Logistics", "Trade Compliance"],
    client: 'Trading Companies',
    date: '2024-06-30',
    liveUrl: '#',
    servicesProvided: ["Commercial Invoice Prep", "Packing List Generation", "Shipping Bill Assistance", "KYC & Agreement Tracking"],
    results: "Facilitated smoother import/export operations by ensuring accurate and compliant documentation.",
    gallery: [
        { src: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxkb2N1bWVudCUyMHRlbXBsYXRlfGVufDB8fHx8MTc1NDQ3MzgwN3ww&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Sample Export Document', dataAiHint: 'document template' },
        { src: 'https://images.unsplash.com/photo-1549419688-353d08f09312?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxvZ2lzdGljcyUyMGNoZWNrbGlzdHxlbnwwfHx8fDE3NTQ0NzM4MDd8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Logistics Workflow Diagram', dataAiHint: 'logistics checklist' },
        { src: 'https://images.unsplash.com/photo-1600880292210-859b923841e7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxjb21wbGlhbmNlJTIwc2VhbHxlbnwwfHx8fDE3NTQ0NzM4MDd8MA&ixlib=rb-4.1.0&q=80&w=1080', alt: 'Compliance Verification Badge', dataAiHint: 'compliance seal' },
    ]
  }
];
